### ISSUE TITLE
Restarting production server automatically when under load

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#108]
systemD might have something - do it by CPU

**Comment by kmp3325** [comment]
I actually couldn't find a way to handle this with systemD sadly...I ended up putting a job in root's crontab to just restart the services when the CPU load is maxed out for more than 15 minutes.  I can't really make a PR for this, so here's the script:

```
CPU_USAGE=$(uptime | cut -d"," -f5 | cut -d":" -f2 | cut -d" " -f2 | sed -e "s/\.//g")
CPU_USAGE_THRESHOLD=200

if [ $CPU_USAGE -gt $CPU_USAGE_THRESHOLD ] ; then
  systemctl restart linguine-node
  systemctl restart linguine-python
fi
```

It's just located in `/home/linguini/restart-on-high-load.sh` on the server.

**Comment by jmp3833** [comment]
Would you mind checking it into the linguine repo and making a PR there? There are scripts for the systemd configs as well so we can keep all of that stuff in one place and documented.

**Comment by kmp3325** [comment]
Oh nice, alright, I'll do that.  Thanks dude!
