### ISSUE TITLE
Visualization - Coreference resolution

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#110]
http://stanfordnlp.github.io/CoreNLP/coref.html

**Comment by daniellegonzalez** [comment]
Potential Idea: 
Gather a list of all the "things" that have references. Create a dropdown of those "things".  Display text and highlight the references to the "thing" selected from dropdown. 

Questions/Concerns: 
1. Words like "it", "that", etc. 
2. What does the data returned from the analysis look like? Do we have to pull the text from elsewhere and then manually overlay results on it, or can we pieces the corpora back together from the results like we did for NER?

**Comment by daniellegonzalez** [comment]
4/7: For every entity, make a dropdown element. For every mention in an entity, find the sentence and the token span, and highlight it.
