### ISSUE TITLE
Wrapping Raw Corpora Text

### ISSUE THREAD

**Issue by meyersbs** [Pastafarians/linguine#121]
The two news articles in the Linguine database have some very long lines, which extend outside of the standard display box. I would like to see some form of text wrapping implemented.
![linguine_word_wrapping](https://cloud.githubusercontent.com/assets/4073851/15031916/94bb575c-122a-11e6-9ef6-e23215e737e5.png)

**Comment by jmp3833** [comment]
Addressed in PR 38 on linguine-node: https://github.com/Pastafarians/linguine-node/pull/38

<img width="784" alt="screen shot 2016-05-10 at 1 30 37 pm" src="https://cloud.githubusercontent.com/assets/1236565/15156097/704f1498-16b3-11e6-9f34-0dcc029356e7.png">

**Comment by jmp3833** [comment]
Merged into master. Closed!
