### ISSUE TITLE
Viewing a large corpus should not freeze the application.

### ISSUE THREAD

**Issue by kmp3325** [Pastafarians/linguine#20]

**Comment by jmp3833** [comment]
Need to perform research to identify exact issues that are causing this

Primary issue: entire browser is locked up waiting for a response when selecting a large corpus. 

Possible solutions:
- [ ] Limiting upload size. Presenting a prompt if a file may be too big to process
- [ ] Potential hard limit on file size

**Comment by kmp3325** [comment]
I think we should still allow corpa of arbitrary size (we can present a warning message if we want), but we should just show a spinner instead of having the browser lock up waiting for a response - a request like this should always be async.

**Comment by jmp3833** [comment]
Right, that makes sense. Hopefully we can find a way to provide more than just a spinner if we know the input is going to take a lot of time. Otherwise providing the message and spinner now would be best

**Comment by kmp3325** [comment]
Agreed, it would be nice if we had a loading bar or percentage, but I feel like that would just be too much work for too little gain.  So I agree, for now we should just do the message and spinner to keep it simple.
