### ISSUE TITLE
Show metadata in the detailed view for an analysis.

### ISSUE THREAD

**Issue by kmp3325** [Pastafarians/linguine#30]
Titles, time stamps, analysis options, etc... should be stored for saved analyses that have been run. This will be useful when checking analyses that have been already performed.

**Comment by kmp3325** [comment]
An analysis should be able to have some metadata associated with it so that you know what you're looking at.
- Title (we need to be able to give custom names to analyses)
- Timestamp
- Analysis Choice
- Preprocessing choices
- Corpus

**Comment by daniellegonzalez** [comment]
PLAN OF ACTION: 
1. model the flow of the analysis data from create new analysis to view existing analysis. It is unclear where data is being persisted. 
2. Modify the schema of the analysis to include a metadata key, with the value being an object containing the desired data
3. When an analysis is being saved to the db, record and add the meta data values

**Comment by daniellegonzalez** [comment]
Having issues with sending the metadata values from OnCreateAnalysis to the python API. It doesn't seem to like the nested object in either the mongoose schema or the 'payload' JSON object because the values are null when they get to the python side..
