### ISSUE TITLE
Change "Word Cloud Generator" to "Term Frequency Analysis"

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#45]
Both Node and Python changes to make 'wordcloudop' coorespond to a term frequency analysis rather than 'word cloud generator' which  is not a specific analysis type.

**Comment by daniellegonzalez** [comment]
Change name of analysis in Node
Change unfriendly name for Python

What function does this call in Python?
Difference between TFIDF?

**Comment by jmp3833** [comment]
In order to accomplish this,  changes need to be made on the Python and Node side. In the Python side, wordcloudop can be changed to a termFrequency method but maintain the same functionality. 

On the node side, The name of the analysis to perform thats passed in the POST just needs to be changed. No infrastructure changes need to be made.

**Comment by jmp3833** [comment]
Fixed in newest PR on Linguine-Node
