### ISSUE TITLE
Selecting Corpus tags should not delete them from the corpus

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#5]
Ideally, The Corpus tags should filter the list of corpora when selected, rather than being deleted. There should be an 'X' icon on each tag that can be used to delete the tag.

**Comment by DanielleGonzalez** [comment]
We should revisit this at some point - what would be a better way to remove tags?
Have a 'remove' button similar to add? The 'buttons' are not actually buttons, they're just spans with an ng-click attribute which removes them. I tried to look for a way to add an 'x' to the span to close it but didn't get far with that. 

For now, I just disabled this, so clicking does nothing but there isn't a way to remove the tag.
