### ISSUE TITLE
Invalid Password bar remains present after good login

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#6]
#### Steps to reproduce:
- Try to login with bogus credentials
- Login with good credentials
- Notice that the invalid login/password bar remains present

**Comment by kmp3325** [comment]
This took way too long for one line of code, but turns out that Kristen's `angular-flash-pure` library was conveniently set up to delete the message on another call of `event:angularFlash` - https://github.com/Pastafarians/linguine-node/blob/master/assets/js/common/flash.js#L31.
