### ISSUE TITLE
NER Tagging with Tooltips

### ISSUE THREAD

**Issue by vastaj** [Pastafarians/linguine#71]
DO THIS BEFORE POS
Adding a visualization (straight text) but has tool tips with the named entity
- gives sentence
- gives tooltips 
  How do we want to display this/how big do we want it?
  How do we convey that there is a tool tip?

**Comment by daniellegonzalez** [comment]
https://github.com/shawnbot/d3-bootstrap

**Comment by daniellegonzalez** [comment]
make a query to the python server using the corpora id to get it back, display it raw and then get the tooltips up ( do highlighting on selected text). add condition for deleted corpus: text "This corpus has been deleted"

**Comment by daniellegonzalez** [comment]
There's something wrong with either my python or my corenlp on my local machine.. I can't test my code at the moment
