### ISSUE TITLE
Documentation - Make Static Site

### ISSUE THREAD

**Issue by jmp3833** [Pastafarians/linguine#78]
Decide the medium - Github site/jekyll/wiki/wordpress??

Configuration - initial creation, deploy onto production

(Each part of the docs would be a different story)

**Comment by daniellegonzalez** [comment]
Deployment wiki

**Comment by jmp3833** [comment]
Wiki with landing page has been created. More documentation stories have been made to describe the individual sections. Closing this bad boy
